### ISSUE TITLE
Craft price is using wrong value of vendor item

### ISSUE THREAD

**Issue by ColdFyre1337** [ErlendEllingsen/wowclassicpricebot-website#4] opened 2020-02-18 22:17 UTC
I tried to get the craft price for an elixir of fortitude but it used 29.9 gold as the value of the Leaded Vial when it is sold by vendors for ~2s.

![craft](https://user-images.githubusercontent.com/44171405/74782959-8cc9b480-5272-11ea-9ad2-09b7f75bca9f.PNG)

**Comment by ErlendEllingsen** [comment] 2020-02-18 22:29
I will fix this, im guessing it will take a day or two.

**Comment by ErlendEllingsen** [comment] 2020-02-19 11:12
Closing this as its a duplicate of #3

**Closed as completed by ErlendEllingsen** 2020-02-19 11:12 UTC
Labels: duplicate
